### ISSUE TITLE
Collect recent errors and make them available

### ISSUE THREAD

**Issue by kevinsawicki** [atom/exception-reporting#10]
Currently when the dev tools pops up it only shows the top of the stack for the errors that were logged.

This can make it hard to tell which package caused it and you have to do the whole open the dev tools first, reproduce the error, get the stack dance.

So start collecting the last 10 or so and make the log-able from dev tools using something like `printRecentErrors()`.

This method could even check the stack and tell you which package it came from by looking for `~/.atom/packages` in the stack.

**Comment by daviwil** [comment]
This issue was moved to atom/atom#18144
