### ISSUE TITLE
Request: Indicate that package is looking for existing issue

### ISSUE THREAD

**Issue by tairun** [atom/exception-reporting#16]
I think its really cool, that the package checks if there is already an open issue on github. But the default button says **Report Error** and if you click it and the issue was in fact already reported, nothing happens. A good 2-3 seconds later the button changes to **View Issue**. I would appreciate it, if there was a visual indicator, that atom is searching online.

**Comment by damieng** [comment]
That part of the functionality is actually handled in the notification package.

**Comment by daviwil** [comment]
This issue was moved to atom/atom#18143
