### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by celson** [atom/exception-reporting#34]
You have the core package "exception-reporting" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (/usr/lib/atom/node_modules/dalek/lib/main.js:14:14)
Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
<unknown> (/usr/lib/atom/src/package-manager.js:506:32)
```

**Comment by 50Wliu** [comment]
> You have the core package "exception-reporting" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
