### ISSUE TITLE
Absolute paths are preventing Bugsnag from grouping exceptions

### ISSUE THREAD

**Issue by nathansobo** [atom/exception-reporting#35]
Take a look at bugsnag and you'll see what I mean. We're getting the same exception reported separately in lots of cases due to too much variation in paths. We need to relativize all paths in stack traces based on the `resourcePath` if we can. Some won't be relative to the resource path and we can leave those absolute.

/cc @iolsen

**Comment by damieng** [comment]
There's a bunch of useful path cleanup in https://github.com/atom/notifications/blob/master/lib/notification-issue.coffee that we use for tidying up stack traces etc. when reporting GH issues to avoid including user home folders etc. that might be useful to re-use.

**Comment by nathansobo** [comment]
Thanks for the info @damieng!
