### ISSUE TITLE
Bugsnag exceptions should reference coffeescript source

### ISSUE THREAD

**Issue by thedaniel** [atom/exception-reporting#9]
@kevinsawicki mentioned that at one point, the exceptions reported to bugsnag had line numbers / stack trace references from the coffeescript source but we seem to have regressed as they are now from the JS:

![screen shot 2014-07-16 at 12 29 41 pm](https://cloud.githubusercontent.com/assets/1476/3604405/dfe690b4-0d1f-11e4-91ec-28d37c390081.png)

**Comment by damieng** [comment]
Closing this as we are moving to JS.
